# Data Transformation in Pandas

In [1]:
import pandas as pd

In [2]:
data=pd.DataFrame({"a":["one","two"]*3,
                   "b":[1,1,2,3,2,3]})
data

a  b
0  one  1
1  two  1
2  one  2
3  two  3
4  one  2
5  two  3

In [3]:
data.duplicated()

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [4]:
data.drop_duplicates()

a  b
0  one  1
1  two  1
2  one  2
3  two  3

In [5]:
data["c"]=range(6)
data

a  b  c
0  one  1  0
1  two  1  1
2  one  2  2
3  two  3  3
4  one  2  4
5  two  3  5

In [6]:
data.duplicated(["a","b"],keep="last")

0    False
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [7]:
df=pd.DataFrame({"names":["Tim","tom","Sam",
                          "kate","Kim"],
                "scores":[60,50,70,80,40]})
df

names  scores
0   Tim      60
1   tom      50
2   Sam      70
3  kate      80
4   Kim      40

In [8]:
classes={"Tim":"A","Tom":"A","Sam":"B",
         "Kate":"B","Kim":"B"}

In [9]:
n=df["names"].str.capitalize()

In [10]:
df["branches"]=n.map(classes)

In [11]:
df

names  scores branches
0   Tim      60        A
1   tom      50        A
2   Sam      70        B
3  kate      80        B
4   Kim      40        B

In [12]:
s=pd.Series([80,70,90,60])
s

0    80
1    70
2    90
3    60
dtype: int64

In [13]:
import numpy as np

In [14]:
s.replace(70,np.nan)

0    80.0
1     NaN
2    90.0
3    60.0
dtype: float64

In [15]:
s.replace([70,60],[np.nan,0])

0    80.0
1     NaN
2    90.0
3     0.0
dtype: float64

In [16]:
s.replace({90:100,60:0})

0     80
1     70
2    100
3      0
dtype: int64

In [17]:
df=pd.DataFrame(
    np.arange(12).reshape(3,4),
    index=[0,1,2],
    columns=["tim","tom","kim","sam"])
df

tim  tom  kim  sam
0    0    1    2    3
1    4    5    6    7
2    8    9   10   11

In [18]:
s=pd.Series(["one","two","three"])
df.index=df.index.map(s)

In [19]:
df

tim  tom  kim  sam
one      0    1    2    3
two      4    5    6    7
three    8    9   10   11

In [20]:
df.rename(index=str.title,columns=str.upper)

TIM  TOM  KIM  SAM
One      0    1    2    3
Two      4    5    6    7
Three    8    9   10   11

In [21]:
df.rename(index={"one":"ten"},
          columns={"sam":"kate"},
          inplace=True)
df

tim  tom  kim  kate
ten      0    1    2     3
two      4    5    6     7
three    8    9   10    11

In [22]:
sc=[30,80,40,90,60,45,95,75,55,100,65,85]

In [23]:
x=[20,40,60,80,100]

In [24]:
y=pd.cut(sc,x)
y

[(20, 40], (60, 80], (20, 40], (80, 100], (40, 60], ..., (60, 80], (40, 60], (80, 100], (60, 80], (80, 100]]
Length: 12
Categories (4, interval[int64, right]): [(20, 40] < (40, 60] < (60, 80] < (80, 100]]

In [25]:
y.codes

array([0, 2, 0, 3, 1, 1, 3, 2, 1, 3, 2, 3], dtype=int8)

In [26]:
y.categories

IntervalIndex([(20, 40], (40, 60], (60, 80], (80, 100]], dtype='interval[int64, right]')

In [27]:
pd.value_counts(y)

(80, 100]    4
(40, 60]     3
(60, 80]     3
(20, 40]     2
Name: count, dtype: int64

In [28]:
y=pd.cut(sc,x,right=False)
y

[[20, 40), [80, 100), [40, 60), [80, 100), [60, 80), ..., [60.0, 80.0), [40.0, 60.0), NaN, [60.0, 80.0), [80.0, 100.0)]
Length: 12
Categories (4, interval[int64, left]): [[20, 40) < [40, 60) < [60, 80) < [80, 100)]

In [29]:
nm=["low", "medium", "high", "very high"]
pd.cut(sc,x,labels=nm)

['low', 'high', 'low', 'very high', 'medium', ..., 'high', 'medium', 'very high', 'high', 'very high']
Length: 12
Categories (4, object): ['low' < 'medium' < 'high' < 'very high']

In [30]:
pd.cut(sc,10)

[(29.93, 37.0], (79.0, 86.0], (37.0, 44.0], (86.0, 93.0], (58.0, 65.0], ..., (72.0, 79.0], (51.0, 58.0], (93.0, 100.0], (58.0, 65.0], (79.0, 86.0]]
Length: 12
Categories (10, interval[float64, right]): [(29.93, 37.0] < (37.0, 44.0] < (44.0, 51.0] < (51.0, 58.0] ... (72.0, 79.0] < (79.0, 86.0] < (86.0, 93.0] < (93.0, 100.0]]

In [31]:
data=np.random.randn(100)
c=pd.qcut(data,4)
c

[(0.755, 1.927], (0.755, 1.927], (-0.872, -0.0674], (-0.0674, 0.755], (-0.872, -0.0674], ..., (-3.5589999999999997, -0.872], (-3.5589999999999997, -0.872], (-0.0674, 0.755], (-3.5589999999999997, -0.872], (-0.872, -0.0674]]
Length: 100
Categories (4, interval[float64, right]): [(-3.5589999999999997, -0.872] < (-0.872, -0.0674] < (-0.0674, 0.755] < (0.755, 1.927]]

In [32]:
pd.value_counts(c)

(-3.5589999999999997, -0.872]    25
(-0.872, -0.0674]                25
(-0.0674, 0.755]                 25
(0.755, 1.927]                   25
Name: count, dtype: int64

In [33]:
data=pd.DataFrame(np.random.randn(1000,4))
data.head()

0         1         2         3
0 -1.078288 -0.070807  0.300003  2.099699
1  1.147872 -0.468422 -0.792492  0.833092
2 -0.340667  1.166388  0.015046  0.422974
3  0.643705 -1.612399  1.239652 -0.745944
4 -0.043893 -1.903778 -1.015534  0.632837

In [34]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.038331     0.064737    -0.083052     0.104158
std       1.008396     0.972638     1.000873     1.000104
min      -2.617513    -3.262547    -3.240580    -2.993304
25%      -0.663066    -0.574332    -0.779396    -0.576664
50%       0.059440     0.068890    -0.087697     0.107982
75%       0.732338     0.697295     0.610910     0.811612
max       3.394412     3.132820     3.218172     3.051595

In [35]:
col=data[1]

In [36]:
col[np.abs(col)>3]

328   -3.262547
432   -3.202794
495    3.132820
850   -3.011643
Name: 1, dtype: float64

In [39]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0  1.0  1.0
1  1.0 -1.0 -1.0  1.0
2 -1.0  1.0  1.0  1.0
3  1.0 -1.0  1.0 -1.0
4 -1.0 -1.0 -1.0  1.0

In [40]:
data=pd.DataFrame(
    np.arange(12).reshape(4,3))
data

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [41]:
rw=np.random.permutation(4)
rw

array([2, 1, 0, 3])

In [42]:
data.take(rw)

0   1   2
2  6   7   8
1  3   4   5
0  0   1   2
3  9  10  11

In [43]:
data.sample()

0   1   2
3  9  10  11

In [44]:
data.sample(n=2)

0   1   2
3  9  10  11
0  0   1   2

## Dummy Variable

In [45]:
data=pd.DataFrame(
    {"letter":["c","b","a","b","b","a"],
                   "number":range(6)})
data

letter  number
0      c       0
1      b       1
2      a       2
3      b       3
4      b       4
5      a       5

In [46]:
pd.get_dummies(data["letter"])

a      b      c
0  False  False   True
1  False   True  False
2   True  False  False
3  False   True  False
4  False   True  False
5   True  False  False

In [47]:
data=np.random.randn(10)
data

array([ 0.84156669,  1.36619289,  0.71683825, -0.09852256,  1.38159798,
        1.1076384 ,  0.80594658, -1.46920237,  1.73731978, -0.92645904])

In [48]:
pd.get_dummies(pd.cut(data,4))

(-1.472, -0.668]  (-0.668, 0.134]  (0.134, 0.936]  (0.936, 1.737]
0             False            False            True           False
1             False            False           False            True
2             False            False            True           False
3             False             True           False           False
4             False            False           False            True
5             False            False           False            True
6             False            False            True           False
7              True            False           False           False
8             False            False           False            True
9              True            False           False           False